//
// arobj_uln2003.hpp
//
// generated by the Ardestan programming language : Tue Dec 03 21:29:04 CST 2019
//

#ifndef __arobj_uln2003_h__
#define __arobj_uln2003_h__


#define ULN2003_NUM_OF_PINS 4
//----------------------------------------------------------------------------
// type
//----------------------------------------------------------------------------


typedef struct {
	int8_t	pins[ULN2003_NUM_OF_PINS]	;
	int8_t	index						;
} ARObjUln2003;

//----------------------------------------------------------------------------
// declaration
//----------------------------------------------------------------------------

void init_func_uln2003(
    ARObject*        self      ,
    void*            __fields__,
    uint_fast8_t     argc      ,
    ARMessageType*   argt      ,
    ARValue*         argv
);

void trigger_func_uln2003(
    ARObject*        self      ,
    int32_t          inlet_no  ,
    void*            __fields__
);
#endif
