//
// arobj_gate.hpp
//
// generated by the Ardestan programming language : Thu Jul 09 15:45:15 CST 2020
//

#ifndef __arobj_gate__h__
#define __arobj_gate__h__
//----------------------------------------------------------------------------
// type
//----------------------------------------------------------------------------

typedef struct {
	int8_t num_outlets;
} ARObjGate;

//----------------------------------------------------------------------------
// declaration
//----------------------------------------------------------------------------

void init_func_gate(
    ARObject*        self      ,
    void*            __fields__,
    uint_fast8_t     argc      ,
    ARMessageType*   argt      ,
    ARValue*         argv
);

void trigger_func_gate(
    ARObject*        self      ,
    int32_t          inlet_no  ,
    void*            __fields__
);
#endif
